# Generated by Django 6.1.1 on 2026-09-16 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FOLK_ART', 'Folk Art'), ('PERFORMANCE', 'Folk Performance'), ('FESTIVAL', 'Festival'), ('FOOD', 'Traditional Food'), ('CRAFT', 'Craft & Technique'), ('LANGUAGE', 'Dialect / Oral Story')], max_length=20)),
                ('description', models.TextField()),
                ('cultural_significance', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('preservation_status', models.CharField(choices=[('ACTIVE', 'Actively Practised'), ('DECLINING', 'Declining'), ('RARE', 'Rare'), ('ENDANGERED', 'Endangered')], default='ACTIVE', max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Published'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
